# 项目相关配置
rifle:
  # 名称
  name: Rifle-fast
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2024

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为6312
  port: 6312
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

  # mysql 配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.197.133:3306/rifle_fast?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID